general:
  label: 基础设置
  items:
    scheme:
      name: scheme
      label: 主题样式
      type: select
      default: Paradox
      options:
        - value: Paradox
          label: Paradox
        - value: Isolation
          label: Isolation

    favicon:
      name: favicon
      label: Favicon
      type: attachment

    high_res_favicon:
      name: high_res_favicon
      label: 高清 Favicon
      type: attachment

    apple_touch_icon:
      name: apple_touch_icon
      label: IOS 主屏按钮图标
      type: attachment

    daily_pic:
      name: daily_pic
      label: 首页头图
      type: attachment

    sidebar_header:
      name: sidebar_header
      label: Sidebar 顶部图片
      type: attachment

    footer_image:
      name: footer_image
      label: Sidebar 底部图片
      type: attachment

style:
  label: 样式设置
  items:
    uiux_slogan:
      name: uiux_slogan
      label: 首页 Slogan
      type: text
      default: 'Hi, nice to meet you'

    uiux_card_elevation:
      name: uiux_card_elevation
      label: 卡片深度
      type: text
      default: '2'

    theme_style:
      name: theme_style
      label: 主题样式设置
      type: radio
      data-type: bool
      default: 0
      options:
        - value: 0
          label: 样式一
        - value: 1
          label: 样式二

    back_to_top:
      name: back_to_top
      label: 切换页面时滑动到顶部
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 是
        - value: false
          label: 否

    list_animation:
      name: list_animation
      label: 文章列表展示动画是否重复动画
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 是
        - value: false
          label: 否

    post_baidu_record:
      name: post_baidu_record
      label: 文章页面是否显示百度收录情况
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 是
        - value: false
          label: 否

    dynamic_title:
      name: dynamic_title
      label: 开启动态标题
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    dynamic_title_leave:
      name: dynamic_title_leave
      label: 动态标题（离开页面时）
      type: text

    dynamic_title_enter:
      name: dynamic_title_enter
      label: 动态标题（离开再次进入时）
      type: text

    backgroun_image:
      name: backgroun_image
      label: 风格二背景图
      type: attachment

    background_filter:
      name: background_filter
      label: 风格二背景图模糊值
      type: text

    site_subtitle:
      name: site_subtitle
      label: 站点副标题
      type: text

    summary:
      name: summary
      label: 首页文章摘要字数
      type: text
      default: '50'
      placeholder: '默认不超过80'

sns:
  label: 社交资料
  items:
    sns_email:
      name: sns_email
      label: Email
      type: text

    sns_facebook:
      name: sns_facebook
      label: Facebook
      type: text

    sns_twitter:
      name: sns_twitter
      label: Twitter
      type: text

    sns_googleplus:
      name: sns_googleplus
      label: Google +
      type: text

    sns_weibo:
      name: sns_weibo
      label: 微博
      type: text

    sns_instagram:
      name: sns_instagram
      label: Instagram
      type: text

    sns_tumblr:
      name: sns_tumblr
      label: Tumblr
      type: text

    sns_github:
      name: sns_github
      label: Github
      type: text

    sns_linkedin:
      name: sns_linkedin
      label: Linkedin
      type: text

    sns_zhihu:
      name: sns_zhihu
      label: 知乎
      type: text

    sns_bilibili:
      name: sns_bilibili
      label: 哔哩哔哩
      type: text

    sns_telegram:
      name: sns_telegram
      label: Telegram
      type: text

    sns_v2ex:
      name: sns_v2ex
      label: V2EX
      type: text

    sns_segmentfault:
      name: sns_segmentfault
      label: Segmentfault
      type: text

sns-share:
  label: 分享设置
  items:
    thumb_nail:
      name: thumb_nail
      label: 分享缩略图
      type: attachment
      placeholder: '在这里填入一个图片 URL 地址，不填也可以'

    sns_share_twitter:
      name: sns_share_twitter
      label: 分享到 Twitter
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    sns_share_facebook:
      name: sns_share_facebook
      label: 分享到 Facebook
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    sns_share_googleplus:
      name: sns_share_googleplus
      label: 分享到 Google +
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    sns_share_weibo:
      name: sns_share_weibo
      label: 分享到微博
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    sns_share_linkedin:
      name: sns_share_linkedin
      label: 分享到 Linkedin
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    sns_share_qq:
      name: sns_share_qq
      label: 分享到 QQ
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    sns_share_telegram:
      name: sns_share_telegram
      label: 分享到 Telegram
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

other:
  label: 其他设置
  items:
    icp:
      name: icp
      label: ICP备案号
      type: text

    public_security_record:
      name: public_security_record
      label: 网安备案号
      type: text

    time_statistics:
      name: time_statistics
      label: 站点运行时间统计
      type: text
      placeholder: '填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00'

    music_list:
      name: music_list
      label: 歌单
      type: textarea
      default: ''
      placeholder: ''

    music_autoplay:
      name: music_autoplay
      label: 是否开启音乐自动播放
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    musicList_folded:
      name: musicList_folded
      label: 音乐列表折叠
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    qr_code_zfb:
      name: thumb_nail
      label: 支付宝二维码链接
      type: attachment


    qr_code_wx:
      name: thumb_nail
      label: 微信二维码链接
      type: attachment